"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Bell, BellRing, Calendar, Clock, Settings } from "lucide-react"

interface NotificationCenterProps {
  upcomingDoses: any[]
}

export default function NotificationCenter({ upcomingDoses }: NotificationCenterProps) {
  const [showNotifications, setShowNotifications] = useState(false)
  const [notificationsEnabled, setNotificationsEnabled] = useState(false)
  const [permission, setPermission] = useState<NotificationPermission>("default")

  useEffect(() => {
    // Check notification permission on mount
    if ("Notification" in window) {
      setPermission(Notification.permission)
      setNotificationsEnabled(Notification.permission === "granted")
    }
  }, [])

  const requestNotificationPermission = async () => {
    if ("Notification" in window) {
      const permission = await Notification.requestPermission()
      setPermission(permission)
      setNotificationsEnabled(permission === "granted")

      if (permission === "granted") {
        // Show a test notification
        new Notification("MedTrack Notifications Enabled", {
          body: "You will now receive medication reminders",
          icon: "/placeholder.svg?height=64&width=64",
        })
      }
    }
  }

  const scheduleNotification = (dose: any) => {
    if (!notificationsEnabled) return

    const now = new Date().getTime()
    const doseTime = new Date(dose.scheduledTime).getTime()
    const timeUntil = doseTime - now

    if (timeUntil > 0) {
      setTimeout(() => {
        new Notification(`Time for ${dose.medicationName}`, {
          body: `Take ${dose.dosage} now`,
          icon: "/placeholder.svg?height=64&width=64",
          tag: dose.medicationId,
          requireInteraction: true,
        })
      }, timeUntil)
    }
  }

  const addToGoogleCalendar = (dose: any) => {
    const startTime = new Date(dose.scheduledTime)
    const endTime = new Date(startTime.getTime() + 15 * 60000) // 15 minutes later

    const event = {
      title: `Take ${dose.medicationName}`,
      start: startTime.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z",
      end: endTime.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z",
      description: `Medication: ${dose.medicationName}\nDosage: ${dose.dosage}\n\nGenerated by MedTrack`,
    }

    const googleCalendarUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(event.title)}&dates=${event.start}/${event.end}&details=${encodeURIComponent(event.description)}`

    window.open(googleCalendarUrl, "_blank")
  }

  const urgentDoses = upcomingDoses.filter((dose) => dose.timeUntil <= 30 * 60 * 1000) // Next 30 minutes
  const hasUrgentDoses = urgentDoses.length > 0

  return (
    <div className="relative">
      <Button
        variant="outline"
        size="icon"
        onClick={() => setShowNotifications(!showNotifications)}
        className={hasUrgentDoses ? "animate-pulse border-red-500" : ""}
      >
        {hasUrgentDoses ? <BellRing className="w-4 h-4 text-red-500" /> : <Bell className="w-4 h-4" />}
        {upcomingDoses.length > 0 && (
          <Badge className="absolute -top-2 -right-2 h-5 w-5 p-0 text-xs">{upcomingDoses.length}</Badge>
        )}
      </Button>

      {showNotifications && (
        <div className="absolute right-0 top-12 w-80 z-50">
          <Card className="shadow-lg border-2">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-lg">Notifications</CardTitle>
                <Button variant="ghost" size="sm" onClick={() => setShowNotifications(false)}>
                  ×
                </Button>
              </div>
              <CardDescription>Upcoming medication reminders</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Notification Settings */}
              <div className="p-3 bg-gray-50 rounded-lg">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm font-medium">Browser Notifications</span>
                  <Badge variant={notificationsEnabled ? "default" : "secondary"}>
                    {notificationsEnabled ? "Enabled" : "Disabled"}
                  </Badge>
                </div>
                {!notificationsEnabled && (
                  <Button size="sm" onClick={requestNotificationPermission} className="w-full">
                    <Settings className="w-3 h-3 mr-2" />
                    Enable Notifications
                  </Button>
                )}
              </div>

              {/* Upcoming Doses */}
              {upcomingDoses.length > 0 ? (
                <div className="space-y-3">
                  <h4 className="font-medium text-sm">Upcoming Doses</h4>
                  {upcomingDoses.slice(0, 5).map((dose, index) => {
                    const isUrgent = dose.timeUntil <= 30 * 60 * 1000
                    const hours = Math.floor(dose.timeUntil / (1000 * 60 * 60))
                    const minutes = Math.floor((dose.timeUntil % (1000 * 60 * 60)) / (1000 * 60))

                    return (
                      <div
                        key={index}
                        className={`p-3 rounded-lg border ${isUrgent ? "border-red-200 bg-red-50" : "border-gray-200 bg-white"}`}
                      >
                        <div className="flex items-start justify-between mb-2">
                          <div>
                            <p className="font-medium text-sm">{dose.medicationName}</p>
                            <p className="text-xs text-gray-600">{dose.dosage}</p>
                          </div>
                          {isUrgent && (
                            <Badge variant="destructive" className="text-xs">
                              Urgent
                            </Badge>
                          )}
                        </div>

                        <div className="flex items-center gap-2 text-xs text-gray-500 mb-2">
                          <Clock className="w-3 h-3" />
                          <span>
                            {new Date(dose.scheduledTime).toLocaleTimeString([], {
                              hour: "2-digit",
                              minute: "2-digit",
                            })}
                          </span>
                          <span>
                            ({hours > 0 ? `${hours}h ` : ""}
                            {minutes}m)
                          </span>
                        </div>

                        <div className="flex gap-2">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => scheduleNotification(dose)}
                            disabled={!notificationsEnabled}
                            className="flex-1 text-xs"
                          >
                            <Bell className="w-3 h-3 mr-1" />
                            Remind
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => addToGoogleCalendar(dose)}
                            className="flex-1 text-xs"
                          >
                            <Calendar className="w-3 h-3 mr-1" />
                            Calendar
                          </Button>
                        </div>
                      </div>
                    )
                  })}
                </div>
              ) : (
                <div className="text-center py-6">
                  <Bell className="w-8 h-8 text-gray-400 mx-auto mb-2" />
                  <p className="text-sm text-gray-500">No upcoming doses</p>
                </div>
              )}

              {/* Quick Actions */}
              <div className="border-t pt-3">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    upcomingDoses.forEach((dose) => scheduleNotification(dose))
                    alert(`Scheduled ${upcomingDoses.length} notifications`)
                  }}
                  disabled={!notificationsEnabled || upcomingDoses.length === 0}
                  className="w-full"
                >
                  Schedule All Reminders
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  )
}
